export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REQUEST_EMAIL_LOGIN_OTP_REQUEST = "REQUEST_EMAIL_LOGIN_OTP_REQUEST";
export const REQUEST_EMAIL_LOGIN_OTP_SUCCESS = "REQUEST_EMAIL_LOGIN_OTP_SUCCESS";
export const REQUEST_EMAIL_LOGIN_OTP_FAILURE = "REQUEST_EMAIL_LOGIN_OTP_FAILURE";

export const VERIFY_EMAIL_LOGIN_OTP_REQUEST = "VERIFY_EMAIL_LOGIN_OTP_REQUEST";
export const VERIFY_EMAIL_LOGIN_OTP_SUCCESS = "VERIFY_EMAIL_LOGIN_OTP_SUCCESS";
export const VERIFY_EMAIL_LOGIN_OTP_FAILURE = "VERIFY_EMAIL_LOGIN_OTP_FAILURE";