export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REQUEST_EMAIL_LOGIN_OTP_REQUEST = "REQUEST_EMAIL_LOGIN_OTP_REQUEST";
export const REQUEST_EMAIL_LOGIN_OTP_SUCCESS = "REQUEST_EMAIL_LOGIN_OTP_SUCCESS";
export const REQUEST_EMAIL_LOGIN_OTP_FAILURE = "REQUEST_EMAIL_LOGIN_OTP_FAILURE";

export const VERIFY_EMAIL_LOGIN_OTP_REQUEST = "VERIFY_EMAIL_LOGIN_OTP_REQUEST";
export const VERIFY_EMAIL_LOGIN_OTP_SUCCESS = "VERIFY_EMAIL_LOGIN_OTP_SUCCESS";
export const VERIFY_EMAIL_LOGIN_OTP_FAILURE = "VERIFY_EMAIL_LOGIN_OTP_FAILURE";



// BLOG Section
export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

// Lead Section
export const GET_CONTACTS_REQUEST = "GET_CONTACTS_REQUEST";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE";

export const CREATE_CONTACT_REQUEST = "CREATE_CONTACT_REQUEST";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_FAILURE = "CREATE_CONTACT_FAILURE";

